# Simple workflow for deploying static content to GitHub Pages
name: Deploy dotnet wasm static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false
      
permissions:
  contents: read
  pages: write
  id-token: write
    
env:
  PUBLISH_DIR: bin/Release/net8.0/publish/wwwroot
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v3
    
    # sets up .NET Core SDK 8
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
        dotnet-quality: 'preview'

    # Install WASM tools
    - name: Install WASM tools
      run: dotnet workload install wasm-tools --include-previews

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish -c Release
    
    # Rewrite base href
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /${{ github.event.repository.name }}/

    # Setup pages
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Publishes release folder
        path: ${{ env.PUBLISH_DIR }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
